### PR TITLE
Bring up to date with MULPIv4.0-I07

### PR DESCRIPTION
**Pull request by jeffhowe60**
Made the following changes to bring the tool up to date with MULPIv4.0-I07:
- filled in the gaps and removed duplicates in the symtable identifiers
- corrected TLVs 24.36 and 25.36 from an aggregate to a ushort
- added TLVs from MULPIv3.1-I25 and MULPIv4.0-I07, except TLVs 103 and 104, which have 2 byte length fields. New decoder/encoder functions would be needed to support the 2 byte lengths.

### CODE REVIEW

**Comment by rlaager** [comment]
This project is basically unmaintained. So unless someone else shows up with more information, I'm inclined to just merge this as is.

@jeffhowe60 Do you have any thoughts on #73 and/or #59? Maybe with your review we could clear out those too.

**Comment by jeffhowe60** [comment]
> @jeffhowe60 Do you have any thoughts on #73 and/or #59? Maybe with your review we could clear out those too.

@rlaager To be honest, I almost included the changes for #73 in my request. I was hesitant because it only had a small subset of the TLVs from HOST2.1-I17. But to assist clear the backlog, I can merge those changes into my branch.

Regarding #59, I am not sure of the submission. I think the parser is trying to convert the sequence <backslash><space> into <space>, which seems like a normal thing to do. I think the change requested instead changes that sequence into <backslash>, removing the <space>.

**Comment by rlaager** [comment]
If you're not sure about #59, we can keep ignoring that. It seems you're knowledgable about #73, so if you can merge that in in whatever fashion is appropriate, I would appreciate that.

Please make sure to retain credit for "Dennis Van Ee <dennis.vanee@vecima.com>" as appropriate--either as the author of the commits if you keep them, or with "Co-authored-by" if you merge things together. I'm fine with (and personally slightly prefer) multiple commits, so don't feel like you _have_ to merge things together.

**Comment by jeffhowe60** [comment]
Changes for #73 have been merged into this request, and will resolve that issue.

**Review by rlaager — APPROVED** [review]

**Review by AdrianSimionov — APPROVED** [review]
I am OK with the changes. What I would extra do, is add test cases for all the newly introduced TLVs. That would protect against breaking backward compatibility.

**Pull request merged**
