### PR TITLE
Fix regression testing.

### PR DESCRIPTION
**Pull request by nickhilliard**
the regression testing in the examples directory rotted over time.  This patch mostly fixes that, which means that it's once again possible to run a reasonable set of tests on the sample config files.

Note that this reverses some of the printf() -> fprintf(stderr) changes which were introduced in 4f5fb8c9 for aesthetic reasons.

### CODE REVIEW

**Comment by rlaager** [comment]
You're absolutely right that the tests have bit-rotted and should be fixed.

I have some questions. First off, does this result in all tests passing for you, or are some still failing? When I run it, I still have 13 of 21 tests fail.

Second, can you clarify why these particular things should go to stdout instead of stderr?

**Comment by nickhilliard** [comment]
docsis20_stresstest.txt is the only one that fails after this commit, and that's by design.  What error messages are you seeing, and on what platform?

re: the reversion from stderr to stdout, the code works by encoding the config files, piping the output off to foo.1.txt, then decoding them and outputting to foo.2.txt.  The test rig then compares blah.txt against both foo.1.txt and foo.2.txt.

When the cfg file is encoded, the docsis command prints the output to stdout, but also prints up the preprocessed file beforehand, which needs to be discarded.  The delimiter between these two parts of the output is the line which reads: "Final Output...".  Unless that line is in stdout, the test rig will get the wrong text in foo.1.txt and the test will fail.

The other text was changed back to stdout because otherwise the test rig prints up junk while it's running.

**Comment by nickhilliard** [comment]
we're talking about different directories.  This commit applies only to the examples/ directory.  I'm still looking at the tests/ directory.

**Comment by AdrianSimionov** [comment]
Nick, I created the test/ directory last year as a temporary solution
because the "make test" solution was not working and I wanted something
quick.

Which saved me many times.

Best solution would be also to move the tests from test/ directory to the
examples/ folder but that takes time. If you do not have time for it you
can just open a issue to keep track of it.

You will also need to update the CI script.

Unfortunately I do not have time now to look into your code. Unless Richard
wants to test/accept the commits, it will have to wait for a few weeks.

Thanks a lot for the changes.
Adrian.

**Comment by nickhilliard** [comment]
this patch isn't really ready.  i'll close this pull request and submit a new one when it's ready.

**Comment by AdrianSimionov** [comment]
I do not know about Richard but I preffer smaller patches. It makes
everything a lot easier to check and blame in the future.

**Comment by nickhilliard** [comment]
most of this patch is removing white space from the .conf files.  I'll rework it so that it makes more sense, and that it also includes the tests directory.

**Comment by rlaager** [comment]
The whitespace fix is obviously correct. I've accepted that much.

**Pull request closed without merging**
